### ISSUE TITLE
Maybe... issue with long.txt?

### ISSUE THREAD

**Issue by mho8** [laboon/CS1632_Spring2018#23]
Now maybe I'm making a dyslexic error but it would appear that in line 97 of 'long.txt':

`97|9f79|Edward>Maria(30):Mzila>Yaa(53):George>Rana(39):George>Pakal(71):Amina>Maria(41):Rana>James(21):Puyi>Anne(49):Amina>Tang(36):SYSTEM>Yaa(100)|1518892465.90871000|fd1b`

The timestamp is 1518892465.90871000

And in line 98 of 'long.txt':

`98|fd1b|Rana>Sheba(21):Wu>Rana(32):George>Pakal(76):Cyrus>Sheba(75):Anne>Kaya(35):Rana>Amina(4):Louis>Peter(15):SYSTEM>Yaa(100)|1518892465.106013000|53b6`

The timestamp is 1518892465.106013000

Hence the error I mentioned to you in 1980. I believe my timestamp_checker method is not flawed so hopefully I'm correct here and not just being oblivious to some digit mis-match.

**Comment by laboon** [comment]
This is slightly confusing, but note that the timestamp should NOT be interpreted as a decimal value.  Rather, it is *number of seconds* *period* *number of nanoseconds since the second started*. 

line 97 timestamp: 90871000
line 98 timestamp: 106013000

or to make it easier to compare, this is equivalent to:

line 97 timestamp: 090871000
line 98 timestamp: 106013000

Note that the value for "nanoseconds since the last second" is greater in line 98 than in line 97, so it is valid.

Does that make sense?

**Comment by laboon** [comment]
Closing after explaining via email
