### ISSUE TITLE
Transaction timestamp error in D3, 100.txt 

### ISSUE THREAD

**Issue by njmullen** [laboon/CS1632_Spring2018#26]
On line 64 of 100.txt for D3, the timestamp for the transaction is 1518893688.8960000 and then the timestamp for line 65 is 1518893688.11869000, which causes the blockchain to be invalid as the second time is older. I think line 64 is supposed to be 1518893687.8960000.

**Comment by mho8** [comment]
This confused me as well, but the timestamp can't actually just be interpreted as a float. The integer after the '.' delimiter is actually the number of nanoseconds passed since the last second.

So 11,869,000 is actually > 8,960,000 nanoseconds.

Thus explaining why bad_seconds_timestamp.txt and bad_nanoseconds_timestamp.txt are separate test files. :D
