### ISSUE TITLE
Deliverable 4, Requirement 1; typo

### ISSUE THREAD

**Issue by npatel0835** [laboon/CS1632_Spring2018#34]
In D4, requirement 1, I think there is a typo in the first statement.

As of now, it reads the output should be, "Welcome, friend, to a land of pure calculation"

However, on the website, it reads "Welcome, friend, to a land of pure calculation."
 Notice that there is a period at the end.

I believe that this is a typo as opposed to a defect.

**Comment by laboon** [comment]
Actually, it is neither.  The relevant requirement states:

1. The homepage shall display the text "Welcome, friend, to a land of pure calculation" as well as "Used for CS1632 Software Quality Assurance, taught by Bill Laboon".  There may or may not be carriage returns ("\n") in either of these texts.

Just because it has to display X does not mean that it cannot display other text besides that.  For example, if I say that a page must display "Copyright Bill Laboon, 2018", that does not mean that it cannot be "Argle bargle snargle. - Copyright Bill Laboon, 2018".  The requirement is still met.  

Similarly, if I say I must display the text "foo" but the text on the page is "foo bar", I have still met the requirement.
