### ISSUE TITLE
+ 1 ISSUE #36

### ISSUE THREAD

**Issue by zachbugay** [laboon/CS1632_Spring2018#36]
Running the following `for file in *_test.rb; do ruby $file;done` repeatedly overwrites the coverage/index.html. Thus, I cannot generate a coverage report for all of my test files.

**Comment by laboon** [comment]
Make a new file, main_test.rb:

In it, start simplecov and require_relative all of the other test files, e.g.

```
require 'simplecov'
SimpleCov.start

require_relative 'foo_test'
require_relative 'bar_test'
require_relative 'baz_test'
```

Running main_test.rb will now give you coverage statistics for the entire project.

**Comment by laboon** [comment]
Adding this in here since people are already pointed here:

Note - do not do SimpleCov.start in foo_test, bar_test, etc.  Just one time in main_test!

If you are getting different results each time you run, make sure that you are not exit-ing in the middle of your production code.  This will cause minitest to end its run.  Since tests are run in pseudorandom order, your test suite will end as soon as exit is called, meaning you will get wildly varying results each time depending on when the test case which calls the exiting method is run.
